### ISSUE TITLE
Failed   <<< aws_robomaker_hospital_world

### ISSUE THREAD

**Issue by juanea** [aws-samples/aws-robomaker-sample-application-pr2-hospital#2]
After following the documentation this is the error I get when I try to build the package.

`cd simulation_ws
rosws update
rosdep install --from-paths src --ignore-src -r -y
colcon build`

`Starting >>> aws_robomaker_hospital_world
Starting >>> pr2_hospital_simulation
Finished <<< pr2_hospital_simulation [0.33s]                                                    
--- stderr: aws_robomaker_hospital_world
CMake Error at cmake_install.cmake:56 (file):
  file INSTALL cannot find
  "/home/juan/aws-robomaker-sample-application-pr2-hospital/simulation_ws/src/deps/aws_robomaker_hospital_world/fuel_models".

make: *** [install] Error 1
---
Failed   <<< aws_robomaker_hospital_world [0.35s, exited with code 2]

Summary: 1 package finished [0.45s]
  1 package failed: aws_robomaker_hospital_world
  1 package had stderr output: aws_robomaker_hospital_world
`
Do you have any idea?

Thank you.

**Comment by jerwallace** [comment]
Hey @juanea,

Thanks for your message, can you check in that the folder **fuel_models** is in the following directory?
`/home/juan/aws-robomaker-sample-application-pr2-hospital/simulation_ws/src/deps/aws_robomaker_hospital_world`

There is a utility, `fuel_utility.py` that will download the required 3D model assets from Ignition Fuel's website. Once downloaded, they should appear in the **fuel_models** directory. By default, the script is set to debug mode, so in the *first run* of `colcon build` you should see the following build output (followed by some debug messages and the downloading of the models).

```
running python3 /ws/simulation_ws/src/deps/aws_robomaker_hospital_world/fuel_utility.py download -m XRayMachine -m IVStand -m BloodPressureMonitor -m BPCart -m BMWCart -m CGMClassic -m StorageRack -m Chair -m InstrumentCart1 -m Scrubs -m PatientWheelChair -m WhiteChipChair -m TrolleyBed -m SurgicalTrolley -m PotatoChipChair -m VisitorKidSit -m FemaleVisitorSit -m AdjTable -m MopCart3 -m MaleVisitorSit -m Drawer -m OfficeChairBlack -m ElderLadyPatient -m ElderMalePatient -m InstrumentCart2 -m MetalCabinet -m BedTable -m BedsideTable -m AnesthesiaMachine -m TrolleyBedPatient -m Shower -m SurgicalTrolleyMed -m StorageRackCovered -m KitchenSink -m Toilet -m VendingMachine -m ParkingTrolleyMin -m PatientFSit -m MaleVisitorOnPhone -m FemaleVisitor -m MalePatientBed -m StorageRackCoverOpen -m ParkingTrolleyMax -d /home/juan/aws-robomaker-sample-application-pr2-hospital/simulation_ws/src/deps/aws_robomaker_hospital_world/fuel_models --verbose 2>&1
```

These following build steps are correct:
```
apt update
rosdep update
cd /home/juan/aws-robomaker-sample-application-pr2-hospital/simulation_ws/
rosws update
rosdep install --from-paths src --ignore-src -r -y
colcon build
```

Perhaps try removing the `/home/juan/aws-robomaker-sample-application-pr2-hospital/simulation_ws/src/deps` folder, then run the above commands again?

**Comment by juanea** [comment]
Thank you @jerwallace I will try it.
I will get back to you if I have any issues.
